### ISSUE TITLE
Can't get internet stations to play

### ISSUE THREAD

**Issue by fornitsumfornis** [bcicen/somacli#3]
Let's be honest, you and I know I am a total noob but I can't get somacli to output sound.  I don't think it is a sound issue because I can get cmus to work just fine out of the terminal.  I can't, however, get somacli to output sound.  I choose the station and it says it is playing but I hear nothing.  Is there some environmental variable I am missing here that I need to declare or something?  I'm at a loss.  I really want to play the metal station.  My system information is below.

Linux Mint -- Sarah 64 bit
Output of uname -r 
     4.4.0-122-generic

**Comment by bcicen** [comment]
Congrats on opening your first Github issue!

It sounds like you may need to install the `mplayer` package via your graphical package manager or commandline (`sudo apt-get -y install mplayer`)

**Comment by bcicen** [comment]
added check for mplayer in https://github.com/bcicen/somacli/commit/f3fa98f6a0856d79062bb21913a03f19ce1cb4ee
